services:
  postgres:
    image: postgres:16
    container_name: larry-postgres
    environment:
      POSTGRES_DB: arbitrage
      POSTGRES_USER: larry
      POSTGRES_PASSWORD: larry
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U larry -d arbitrage || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
    networks:
      - mynetwork

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:v0.15.0
    container_name: larry-pg-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://larry:larry@172.20.0.2:5432/arbitrage?sslmode=disable"
    depends_on:
      - postgres
    ports:
      - "9187:9187"
    networks:
      - mynetwork
    restart: always

volumes:
  pgdata:

networks:
  mynetwork:
    external: true