global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "arbitrage-service"
    static_configs:
      - targets: ["localhost:8000"]
    metrics_path: "/metrics"
    scrape_interval: 5s
