global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "arbitrage-service"
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets: ["hoosein-arbitrage-service.liara.run"]
